#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
keywords.py - Earthquake and emergency related keyword database

While the license is GPLv3 as usual, the actual data are believed to be in the public domain,
as they do not constitute a work but simply a collection of terms.

This file is part of the "Brainstorm" distribution (https://github.com/luccoj/earthquakes-bot).
Copyright (c) 2016-2023 Lorenzo J. Lucchini (ljlbox@tiscali.it)

This program is free software: you can redistribute it and/or modify  
it under the terms of the GNU General Public License as published by  
the Free Software Foundation, version 3.
This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
General Public License for more details.
You should have received a copy of the GNU General Public License 
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""

keywords = {}

def get(keyword, language=None):
   if language:
      return keywords.get(keyword, {}).get(language) or []
   else:
      return [word for sublist in keywords.get(keyword, {}).values() for word in sublist]

def contained(keyword, text, languages=[None]):
   for language in languages:
      for word in get(keyword, language) + [keyword]:
         if word in text or word.lower() in text.lower() or word.upper() in text.upper(): return word

   return False




keywords[u'earthquake'] = {
 'eu': [u'lurrikara'],
 'vi': [u'động đất', u'dong dat', u'địa chấn', u'dia chan'],
 'gu': [u'ભૂકંપ', u'ધરતીકંપ', u'bhukampa', u'bhukamp'],
 'az': [u'zəlzələ'],
 'ga': [u'crith talún'],
 'sl': [u'potres'],
 'bs': [u'zemljotres'],
 'ru': [u'землетрясение', u'потрясение', u'zemletryaseniye'],
 'mn': [u'газар хөдлөлт', u'газар ходлол'],
 'ceb': [u'linog'],
 'st': [u'tšisinyeho ea lefatše'],
 'ca': [u'terratrèmol'],
 'lo': [u'ແຜ່ນດິນໄຫວ'],
 'ny': [u'chivomezi'],
 'zu': [u'ukuzamazama komhlaba'],
 'zh-TW': [u'地震'],
 'be': [u'землятрус'],
 'so': [u'dhulgariir'],
 'gl': [u'terremoto'],
 'hy': [u'երկրաշարժ'],
 'sr': [u'земљотрес', u'zemljotres'],
 'su': [u'lindu'],
# 'ja': [u'地震', u'緊急地震速報', u'地震速報', u'揺れた', u'ゆれた', u'揺れています', u'ゆれています'],
 'ja': [u'地震', u'揺れた', u'ゆれた', u'揺れました', u'揺れ', u'揺れています', u'ゆれています', u'津波'],
 'ka': [u'მიწისძვრა'],
 'mr': [u'भूकंप', u'bhukamp', u'bhukampa'],
 'pt': [u'terremoto', u'tremor de terra', u'sismo', u'tremor'],
 'sw': [u'tetemeko la ardhi', u'tetemeko'],
 'nl': [u'aardbeving', u'beving trilling'],
 'km': [u'ការរញ្ជួយដី'],
 'fr': [u'séisme', u'tremblement de terre', u'seisme'],
 'yo': [u'ìṣẹlẹ', u'isele'],
 'is': [u'jarðskjálfti', u'jarðskjálfta', u'jarðskjálftinn'],
 'no': [u'jordskjelv', u'jordskjelvet'],
 'cy': [u'daeargryn'],
 'fa': [u'زلزله', u'زمين لرزه'],
 'lv': [u'zemestrīce'],
 'ms': [u'gempa bumi'],
 'iw': [u'רעידת אדמה', u'רַעַשׁ אַדֲמָה'],
 'hr': [u'potres'],
 'uz': [u'zilzila'],
 'my': [u'ငလျင်'],
 'sq': [u'tërmet', u'termet', u'tërmeti', u'termeti', u'tërmetit', u'termetit', u'tërmetin', u'termetin'],
 'tg': [u'заминҷунбии'],
 'bg': [u'земетресение'],
 'mg': [u'horohoron-tany'],
 'ht': [u'tranbleman tè'],
 'pa': [u'ਭੂਚਾਲ', u'bhucala', u'bhucal'],
 'ps': [u'زلزله', u'چاودنه'],
 'kn': [u'ಭೂಕಂಪ', u'ನೆಲಗುಡುಗು', u'ನೆಲನಡುಕ', u'bhukampa', u'bhukamp'],
 'sk': [u'zemetrasenie'],
 'zh': [u'地震'],
 'th': [u'แผ่นดินไหว'],
 'ta': [u'நிலநடுக்கம்', u'நில நடுக்கம்', u'பூகம்பம்', u'phukampam'],
 'yi': [u'ערד-ציטערניש'],
 'hi': [u'भूकंप', u'भूकम्प', u'भूचाल', u'bhukamp', u'bhu kamp', u'bhuchaal', u'boochaal', u'विस्फोट', u'visphot'],
 'uk': [u'землетрус'],
 'af': [u'aardbewing'],
 'da': [u'jordskælv', u'jordskælvet'],
 'kk': [u'зілзала'],
 'ar': [u'زلزال', u'الزلزال', u'إنذار تسونامي', u'هزة أرضية', u'zilzal'],
 'es': [u'sismo', 'temblor', u'terremoto', u'temblor', u'sisma', u'remezon', u'remezón', u'alerta sísmica', u'alerta sismica', u'TenemosSismo', u'activacion sensor sismico'],
 'hu': [u'földrengés'],
 'it': [u'terremoto', u'sisma'],
 'mt': [u'terremot'],
 'ur': [u'زلزلے', u'بھوکمپیی الرٹ', u'زلزلہ', u'دھماکہ'],
 'tl': [u'lindol', u'panlindol', u'linog'],
 'en': [u'earthquake', u'shakealert', u'seismic alert', u'aftershock', u'temblor', u'tremblor'],
 'lt': [u'žemės drebėjimas'],
 'cs': [u'zemětřesení'],
 'ko': [u'지진'],
 'tr': [u'deprem', u'zelzele', u'sarsıntı', u'yer sarsıntısı', u'sismik uyarı', u'sismik uyari', u'erdhej', u'erdhejî', u'artçı', u'artçılar', u'sallanıyoruz', u'sallandık', u'sarsıldı', u'sarsıldık'],
 'te': [u'భూకంప', u'bhukamp', u'bhukampa', u'bhukampam'],
 'ml': [u'ഭൂമികുലുക്കം', u'bhumikulukkam'],
 'si': [u'භුමි කම්පාව', u'kampava'],
 'id': [u'gempa bumi', u'lindu'],
 'de': [u'Erdbeben', u'Explosion'],
 'bn': [u'ভূমিকম্প', u'ভূকম্পন', u'bhumikampa', u'bhukamp', u'bhumikamp'],
 'et': [u'maavärin', u'maavarin', u'maavärisemine'],
 'el': [u'σεισμός', u'σεισμό' u'seismos', u'seismo', u'κουνηθήκαμε', u'κουνιέμαι', u'σεισιμική δόνηση'],
 'ne': [u'भूकम्प', u'bhukampa', u'bhukamp'],
 'sv': [u'jordbävning', u'jordbävningen', u'jordskalv', u'jordstöt', u'jordskakning'],
 'mi': [u'rūwhenua', u'ruwhenua'],
 'ro': [u'cutremur', u'cutremurul', u'seism'],
 'ha': [u'girgizar kasa'],
 'jw': [u'lindhu'],
 'ig': [u'ala ọma jijiji'],
 'fi': [u'maanjäristys', u'maan vavahtelu'],
 'pl': [u'trzęsienie ziemi', u'trzesienie ziemi', u'wstrząs ziemi', u'wstrzas ziemi'],
 'hmn': [u'earthquake'],
 'zh-CN': [u'地震'],
 'mk': [u'земјотрес']
}



keywords[u'alert'] = {
 'ar': [u'انفجار', u'صفارة إنذار', u'صفارات الانذار '],
 'ru': [u'Взрыв', u'бомбить', u'ракета', u'ракеты', u'снаряд', u'снаряды', u'пули', u'нападение', u'атака', u'танки', u'сирена', u'сирены', u'радиация', u'отключение', u'бомбардировка'],
 'ja': [u'爆発', u'津波', u'ミサイル'],
# 'fr': [u'explosion'],
 'fa': [u'انفجار'],
 'uk': [u'вибух', u'бомба', u'бомби', u'авіабомби', u'напад', u'ракета', u'ракети', u'снаряд', u'кулі', u'танки', u'сирена', u'сирени', u'радіація', u'відключення', u'бомбардування', u'загорівся', u'горить'],
 'ar': [u'انفجار', u'صاروخ '],
# 'es': [u'explosión', u'bomba'],
 'it': [u'esplosione', u'bomba', u'tromba d\'aria', u'blackout', u'black-out', u'black out', u'sparatoria'], #u'missile'
 'ur': [u'دھماکہ'],
 'en': [u'explosion', u'sonic boom', u'outage', u'flash flood', u'tornado watch', u'tornado warning', u'tornado siren', u'tornado', u'tsunami', u'siren', u'sirens', u'air raid', u'air alarm', u'air alert'],  # "missile" triggers silly football stuff
 'tr': [u'patlama', u'bomba', u'füze'],
# 'de': [u'Explosion'],
 'ro': [u'explozie', u'rachetă', u'misil', u'bombă', u'sirenă', u'sirene'],
 'pl': [u'eksplozja', u'pocisk'], #, u'bomba'],
# 'zh': [u'爆炸', u'炸弹'],
}



keywords[u'earthquake warning'] = {
 'hy': [u'Երկրաշարժ նախազգուշացում'],
 'fr': [u'Avertissement sismique'],
 'tg': [u'огоҳӣ заминларза'],
 'it': [u'Allarme terremoto', u'Allarme sismico'],
 'my': [u'ငလျင်သတိပေးခကျြကို'],
 'mn': [u'Газар хөдлөлт анхааруулах'],
 'de': [u'Erdbebenwarnung'],
 'cs': [u'varování zemětřesení'],
 'si': [u'භූමිකම්පා අනතුරු ඇඟවීමක්'],
 'gu': [u'ભૂકંપ ચેતવણી'],
 'sr': [u'земљотрес упозорење'],
 'kk': [u'Жер сілкінісі туралы ескерту'],
 'zu': [u'Umbiko wokuzamazama komhlaba'],
 'ar': [u'تنبيه: زلزال'],
 'zh-TW': [u'地震預警'],
 'mi': [u'Whakatūpato he rū whenua'],
 'fa': [u'هشدار دهنده زلزله'],
 'pa': [u'ਭੂਚਾਲ ਦੀ ਚੇਤਾਵਨੀ'],
 'ja': [u'地震警報', u'地震報告', u'地震速報', u'緊急地震速報'],
 'mt': [u'Twissija terremot'],
 'te': [u'భూకంప హెచ్చరిక'],
 'fi': [u'Maanjäristys varoitus'],
 'el': [u'προειδοποιηση σεισμου'],
 'ha': [u'Girgizar Kasa gargadi'],
 'ceb': [u'linog pasidaan'],
 'th': [u'เตือน แผ่นดินไหว'],
 'da': [u'Advarsel Jordskælv'],
 'gl': [u'Alerta de terremoto'],
 'vi': [u'cảnh báo động đất'],
 'ru': [u'предупреждения землетрясений'],
 'uz': [u'Zilzila ogohlantirish'],
 'ur': [u'زلزلہ کے انتباہ'],
 'bg': [u'за предупреждение за земетресения'],
 'et': [u'Maavärin hoiatuse'],
 'be': [u'папярэджання землятрусаў'],
 'ro': [u'Avertizare cutremur'],
 'yi': [u'ערדציטערניש ווארענונג'],
 'sv': [u'Jordbävning varning'],
 'bn': [u'ভূমিকম্প সতর্কতা'],
 'hu': [u'földrengés figyelmeztetés'],
 'hi': [u'भूकंप की चेतावनी'],
 'jw': [u'Warning lindhu'],
 'zh-CN': [u'地震预警'],
 'st': [u'tšisinyeho ea lefatše e ka bang temoso'],
 'ne': [u'भूकम्प चेतावनी'],
 'ms': [u'Amaran gempa bumi'],
 'id': [u'Peringatan gempa'],
 'hr': [u'Upozorenje o potresu'],
 'ko': [u'지진 경보', u'긴급지진속보'],  # 긴급지진속보
 'es': [u'Alerta de sismo', u'alerta sísmica', u'AlertaSismica', u'AlertaSísmica'],
 'yo': [u'ìṣẹlẹ Ikilọ'],
 'pl': [u'Raport o trzęsieniu ziemi'],
 'bs': [u'Upozorenje Earthquake'],
 'ta': [u'பூகம்ப எச்சரிக்கை'],
 'pt': [u'Alerta de terremoto'],
 'eu': [u'Lurrikara abisua'],
 'is': [u'Jarðskjálfti viðvörun'],
 'ig': [u'Ala ọma jijiji ịdọ aka ná ntị'],
 'kn': [u'ಭೂಕಂಪ ಎಚ್ಚರಿಕೆ'],
 'sw': [u'Onyo la tetemeko la ardhi'],
 'mg': [u'Horohoron-tany fampitandremana'],
 'su': [u'Warning lini'],
 'ny': [u'Chivomezi chenjezo'],
 'mr': [u'भूकंप चेतावणी'],
 'iw': [u'אזהרת רעידת אדמה'],
 'tl': [u'Lindol babala'],
 'hmn': [u'Earthquake warning'],
 'ka': [u'მიწისძვრის გაფრთხილება'],
 'af': [u'waarskuwing aardbewing'],
 'lo': [u'ເຕືອນ ໄພແຜ່ນດິນໄຫວ'],
 'uk': [u'попередження землетрусів'],
 'no': [u'Jordskjelv advarsel'],
 'ca': [u'Advertència terratrèmol'],
 'ga': [u'Rabhadh Earthquake'],
 'ht': [u'Avètisman tranbleman tè'],
 'tr': [u'Deprem uyarısı'],
 'so': [u'Digniin Dhulgariirka'],
 'km': [u'ការព្រមានពីគ្រោះរញ្ជួយដី'],
 'sk': [u'Varovanie zemetrasenie'],
 'mk': [u'предупредување земјотрес'],
 'lv': [u'Zemestrīce brīdinājums'],
 'en': [u'Earthquake warning'],
 'cy': [u'Rhybudd daeargryn'],
 'nl': [u'Waarschuwing aardbeving'],
 'zh': [u'地震预警'],
 'sl': [u'Opozorilo potres'],
 'az': [u'Zəlzələ xəbərdarlığı'],
 'ml': [u'ഭൂകമ്പത മുന്നറിയിപ്പ്'],
 'sq': [u'tërmeti paralajmërim'],
 'lt': [u'Žemės drebėjimas įspėjimo']
}


keywords[u'possible tsunami'] = {
 'jw': [u'bisa tsunami'],
 'ko': [u'쓰나미 발생 가능'],
 'it': [u'possibile tsunami'],
 'ig': [u'o kwere omume mbufịt'],
 'my': [u'ဖြစ်နိုင်သမျှဆူနာမီ'],
 'hy': [u'հնարավոր է tsunami'],
 'bg': [u'възможно цунами'],
 'ht': [u'posib tsunami'],
 'tr': [u'olası tsunami'],
 'eu': [u'posible tsunami'],
 'fr': [u'possible tsunami'],
 'az': [u'mümkün sunami'],
 'hmn': [u'possible tsunami'],
 'mn': [u'боломжтой цунами'],
 'gu': [u'શક્ય સુનામી'],
 'mk': [u'можно цунами'],
 'be': [u'магчыма цунамі'],
 'mt': [u'possibbli tsunami'],
 'el': [u'δυνατό τσουνάμι'],
 'iw': [u'צונאמי אפשרי'],
 'bn': [u'সম্ভাব্য সুনামির'],
 'ja': [u'可能な津波'],
 'es': [u'posible tsunami'],
 'si': [u'සුනාමි අනතුරු'],
 'zu': [u'kungenzeka tsunami'],
 'en': [u'possible tsunami'],
 'mi': [u'āniwhaniwha taea'],
 'ha': [u'm tsunami'],
 'uk': [u'можливе цунамі'],
 'th': [u'สึนามิ ที่เป็นไปได้'],
 'fa': [u'سونامی ممکن'],
 'kn': [u'ಸಾಧ್ಯ ಸುನಾಮಿ'],
 'pl': [u'możliwe tsunami'],
 'mr': [u'शक्य त्सुनामी'],
 'vi': [u'có thể sóng thần'],
 'ro': [u'posibil tsunami'],
 'nl': [u'mogelijke tsunami'],
 'ta': [u'சுனாமி'],
 'te': [u'సాధ్యం సునామీ'],
 'ru': [u'возможно цунами'],
 'so': [u'tsunami suurto gal'],
 'af': [u'moontlike tsoenami'],
 'bs': [u'mogući cunami'],
 'yi': [u'מעגלעך צונאַמי'],
 'hr': [u'moguće tsunami'],
 'fi': [u'mahdollinen tsunami'],
 'cs': [u'je to možné tsunami'],
 'ny': [u'zotheka madzi osefukira'],
 'ur': [u'ممکن سونامی'],
 'lv': [u'iespējams cunami'],
 'et': [u'võimalik tsunami'],
 'sw': [u'inawezekana tsunami'],
 'ml': [u'സാധ്യമായ സുനാമി'],
 'kk': [u'ықтимал цунами'],
 'tg': [u'сунамӣ имконпазир'],
 'yo': [u'ṣee ṣe tsunami'],
 'km': [u'រលកយក្សស៊ូណាអាចធ្វើទៅបាន'],
 'ka': [u'შესაძლებელია ცუნამის'],
 'la': [u'possible tsunami'],
 'hi': [u'संभव सूनामी'],
 'is': [u'hægt Tsunami'],
 'lt': [u'galima cunamis'],
 'id': [u'mungkin tsunami'],
 'ceb': [u'posible nga tsunami'],
 'st': [u'ho ka khonehang tsunami e'],
 'pa': [u'ਸੰਭਵ ਸੁਨਾਮੀ'],
 'ps': [u'د زلزلې خبرداری'],
 'ar': [u'من الممكن تسونامي'],
 'cy': [u'tsunami posib'],
 'no': [u'mulig tsunami'],
 'ne': [u'सम्भव सुनामी'],
 'ga': [u'tsunami féideartha'],
 'pt': [u'possível tsunami'],
 'zh-TW': [u'可能的海嘯'],
 'eo': [u'possible tsunami'],
 'mg': [u'azo atao tsunami,'],
 'su': [u'mungkin tsunami'],
 'tl': [u'posibleng tsunami'],
 'hu': [u'lehetséges cunami'],
 'sv': [u'möjligt tsunami'],
 'gl': [u'posible tsunami'],
 'zh': [u'可能的海啸'],
 'ms': [u'mungkin tsunami'],
 'ca': [u'possible tsunami'],
 'de': [u'möglicher Tsunami'],
 'sq': [u'tsunami mundur'],
 'sl': [u'mogoče cunami'],
 'lo': [u'ຊູນາມິ ທີ່ເປັນໄປໄດ້'],
 'da': [u'mulig tsunami'],
 'sr': [u'могуће цунами'],
 'uz': [u'iloji tsunami'],
 'sk': [u'je to možné cunami'],
 'zh-CN': [u'可能的海啸']
}


keywords[u'weak'] = {
 'bg': [u'лек', u'слаб'],
 'bn': [u'লাইটওয়েট', u'দুর্বল'],
 'et': [u'kerge', u'nõrk'],
 'kn': [u'ಹಗುರವಾದ', u'ದುರ್ಬಲ'],
 'bs': [u'lak', u'slab'],
 'zh-CN': [u'轻量级', u'弱'],
 'tg': [u'қабул намояд', u'суст'],
 'ar': [u'وزن خفيف', u'ضعيف'],
 'iw': [u'קל', u'חלש'],
 'ur': [u'ہلکا پھلکا', u'کمزور'],
 'ml': [u'കനംകുറഞ്ഞ', u'ദുർബലമായ'],
 'ca': [u'lleuger', u'feble'],
 'el': [u'αδύναμος', u'αδύναμη', u'ελαφρύ'],
 'cs': [u'lehká váha', u'slabý'],
 'fi': [u'kevyt', u'heikko'],
 'pa': [u'ਹਲਕਾ', u'ਕਮਜ਼ੋਰ'],
 'ps': [u'کمزوری'],
 'tl': [u'magaan ang timbang', u'mahina'],
 'st': [u'bobebe', u'fokolang'],
 'sq': [u'peshë e lehtë', u'i dobët'],
 'eu': [u'arin', u'ahula'],
 'tr': [u'hafif', u'zayıf'],
 'hi': [u'हल्के', u'निर्बल'],
 'hu': [u'könnyűsúlyú', u'gyenge'],
 'zu': [u'engasindi', u'ebuthakathaka'],
 'ny': [u'opepuka', u'ofooka'],
 'lt': [u'lengvas', u'silpnas'],
 'lo': [u'light', u'ອ່ອນແອ'],
 'uk': [u'легкий', u'слабкий'],
 'my': [u'ပေါ့ပါးတဲ့', u'အားနည်းသော'],
 'ht': [u'ki lejè', u'fèb'],
 'jw': [u'entheng', u'banget'],
 'yo': [u'light', u'lagbara'],
 'mg': [u'maivana', u'malemy'],
 'sk': [u'ľahká váha', u'slabý'],
 'ja': [u'軽量', u'弱い', u'軽い', u'軽く', u'震度0', u'震度1', u'震度2', u'震度3'],
 'pl': [u'lekki', u'słaby'],
 'hy': [u'թեթեւաքաշ', u'թույլ'],
 'ms': [u'ringan', u'lemah'],
 'so': [u'miisaanka yar', u'daciif'],
 'no': [u'lettvekt', u'svak'],
 'mr': [u'हलके', u'कमकुवत'],
 'gu': [u'હળવા', u'નબળા'],
 'fr': [u'léger', u'légere', u'faible'],
 'ceb': [u'lightweight', u'huyang nga'],
 'ne': [u'हल्का', u'कमजोर'],
 'da': [u'letvægts', u'svag'],
 'sr': [u'лак', u'слаб'],
 'uz': [u'engil', u'kuchsiz'],
 'ro': [u'categorie ușoară', u'slab'],
 'hr': [u'lak', u'slab'],
 'lv': [u'viegls', u'vājš'],
 'su': [u'light', u'leuleus'],
 'kk': [u'жеңіл', u'әлсіз'],
 'az': [u'yüngül', u'zəif'],
 'si': [u'සැහැල්ලු', u'දුර්වල'],
 'ko': [u'경량의', u'약한'],
 'mi': [u'Kōmāmā', u'ngoikore'],
 'ru': [u'легкий', u'слабый'],
 'ka': [u'მსუბუქი', u'სუსტი'],
 'pt': [u'leve', u'fraco'],
 'nl': [u'licht', u'zwak'],
 'zh': [u'轻量级', u'弱'],
 'gl': [u'leve', u'feble'],
 'id': [u'ringan', u'lemah'],
 'ha': [u'hur', u'm'],
 'en': [u'light', u'weak', u'small', u'baby', u'tiny', u'mild', u'mini'],
 'is': [u'léttur', u'veik'],
 'it': [u'leggero', u'leggera', u'debole', u'scossetta', u'scossettina'],
 'ta': [u'இலகுரக', u'பலவீனமான'],
 'be': [u'лёгкі', u'слабы'],
 'vi': [u'trọng lượng nhẹ', u'Yếu'],
 'af': [u'liggewig', u'swak'],
 'de': [u'leicht', u'schwach'],
 'ga': [u'lightweight', u'lag'],
 'te': [u'తేలికైన', u'బలహీనమైన'],
 'mt': [u'ħfief', u'dgħajfa'],
 'mn': [u'хөнгөн', u'сул'],
 'km': [u'ទម្ងន់ស្រាល', u'ការចុះខ្សោយ'],
 'th': [u'มีน้ำหนักเบา', u'อ่อนแอ'],
 'sl': [u'lahki', u'šibko'],
 'ig': [u'fechaa', u'-adịghị ike'],
 'es': [u'ligero', u'ligera', u'débil', u'débiles', u'leve', u'suave', u'suavecito', u'chiquito', u'pequeño', u'pequeñito', u'baja', u'menor', u'temblorcito', u'mini', u'remezon', u'remezón'],
 'mk': [u'лесен', u'слаб'],
 'fa': [u'سبک وزن', u'ضعیف'],
 'sv': [u'lätt', u'svag'],
 'zh-TW': [u'輕量級', u'弱'],
 'cy': [u'ysgafn', u'wan'],
 'sw': [u'light', u'dhaifu'],
 'yi': [u'לייטווייט', u'שוואַך'],
}


keywords[u'strong'] = {
 'eu': [u'indartsu'],
 'vi': [u'mạnh'],
 'gu': [u'મજબૂત'],
 'az': [u'güclü'],
 'la': [u'strong'],
 'ga': [u'láidir'],
 'sl': [u'močna','mocna'],
 'bs': [u'jak'],
 'ru': [u'сильный'],
 'mn': [u'хүчтэй'],
 'ceb': [u'lig-on'],
 'st': [u'matla'],
 'ca': [u'fort'],
 'lo': [u'ທີ່ເຂັ້ມແຂງ'],
 'ny': [u'amphamvu'],
 'zu': [u'strong'],
 'zh-TW': [u'強大'],
 'be': [u'моцны'],
 'so': [u'xoog'],
 'gl': [u'forte'],
 'hy': [u'ուժեղ'],
 'sr': [u'јак'],
 'su': [u'kuat'],
 'ja': [u'強い', u'強く', u'強震', u'震度4', u'震度5'],
 'eo': [u'strong'],
 'ka': [u'ძლიერი'],
 'mr': [u'मजबूत'],
 'pt': [u'forte', u'poderoso', u'potente', u'possante'],
 'sw': [u'nguvu'],
 'nl': [u'sterk'],
 'km': [u'ខ្លាំង'],
 'fr': [u'fort'],
 'yo': [u'lagbara'],
 'is': [u'sterkur'],
 'no': [u'sterk'],
 'cy': [u'cryf'],
 'fa': [u'قوی'],
 'lv': [u'stiprs'],
 'ms': [u'kuat'],
 'iw': [u'חָזָק'],
 'hr': [u'jak'],
 'uz': [u'kuchli'],
 'my': [u'အားကြီးသော'],
 'sq': [u'i fortë'],
 'tg': [u'мустаҳкам'],
 'bg': [u'силен'],
 'mg': [u'mahery'],
 'ht': [u'fò'],
 'pa': [u'ਮਜ਼ਬੂਤ'],
 'ps': [u'قوي'],
 'kn': [u'ಬಲವಾದ'],
 'sk': [u'silný'],
 'zh': [u'强大'],
 'th': [u'แข็งแรง'],
 'ta': [u'வலுவான'],
 'yi': [u'שטאַרק'],
 'hi': [u'बलवान', u'तेज़', u'tez', u'teza'],
 'uk': [u'сильний'],
 'af': [u'sterk'],
 'da': [u'stærk'],
 'kk': [u'күшті'],
 'ar': [u'قوي'],
 'es': [u'fuerte', u'poderoso', u'grande', u'largo', u'horrible', u'violento', u'violenta', u'AlertaSismica'],
 'hu': [u'erős'],
 'it': [u'forte'],
 'mt': [u'qawwija'],
 'ur': [u'مضبوط'],
 'tl': [u'malakas'],
 'en': [u'strong'],
 'lt': [u'stiprus'],
 'cs': [u'silný'],
 'ko': [u'강한'],
 'tr': [u'güçlü'],
 'te': [u'బలమైన'],
 'ml': [u'ശക്തമായ'],
 'si': [u'ශක්තිමත්'],
 'id': [u'kuat'],
 'de': [u'stark'],
 'bn': [u'শক্তিশালী'],
 'et': [u'tugev'],
 'el': [u'ισχυρός', u'δυναμός', u'δυναμό', u'δυνατύς', u'δυνατύ', u'δυνατός', u'δυνατό'],
 'ne': [u'बलियो'],
 'sv': [u'stark'],
 'mi': [u'kaha'],
 'ro': [u'puternic'],
 'ha': [u'm'],
 'jw': [u'kuwat'],
 'ig': [u'ike'],
 'fi': [u'vahva'],
 'pl': [u'silny'],
 'hmn': [u'strong'],
 'zh-CN': [u'强大'],
 'mk': [u'силна']
}


keywords[u'very strong'] = {
 'eu': [u'oso indartsua'],
 'vi': [u'rất mạnh'],
 'gu': [u'એકદમ મજબુત'],
 'az': [u'çox güclü'],
 'la': [u'very strong'],
 'ga': [u'an-láidir'],
 'sl': [u'zelo močno'],
 'bs': [u'vrlo jak'],
 'ru': [u'очень сильный'],
 'mn': [u'маш хүчтэй'],
 'ceb': [u'kaayo lig-on nga'],
 'st': [u'matla haholo'],
 'ca': [u'molt fort'],
 'lo': [u'ແຂງ\u200bແຮງ\u200bຫຼາຍ'],
 'ny': [u'kwambiri'],
 'zu': [u'enamandla kakhulu'],
 'zh-TW': [u'非常強壯'],
 'be': [u'вельмі моцны'],
 'so': [u'aad u xoogan'],
 'gl': [u'moi forte'],
 'hy': [u'շատ ուժեղ'],
 'sr': [u'веома јако'],
 'su': [u'pohara kuat'],
 'ja': [u'とても強い', u'非常に強い', u'震度6'],
 'eo': [u'very strong'],
 'ka': [u'ძალიან ძლიერი'],
 'mr': [u'अतिशय मजबूत'],
 'pt': [u'muito forte', u'muito poderoso', u'muito possante', u'muito potente'],
 'sw': [u'nguvu sana'],
 'nl': [u'heel sterk'],
 'km': [u'ខ្លាំង\u200bណាស់'],
 'fr': [u'très fort'],
 'yo': [u'gan lagbara'],
 'is': [u'mjög sterkt'],
 'no': [u'veldig sterk'],
 'cy': [u'cryf iawn'],
 'fa': [u'بسیار قوی'],
 'lv': [u'ļoti stiprs'],
 'ms': [u'sangat kuat'],
 'iw': [u'חזק מאוד'],
 'hr': [u'vrlo jak'],
 'uz': [u'juda kuchli'],
 'my': [u'အလွန်အားကြီးသော'],
 'sq': [u'shume i forte'],
 'tg': [u'хеле қавӣ'],
 'bg': [u'много силен'],
 'mg': [u'tena mahery'],
 'ht': [u'trè fò'],
 'pa': [u'ਬਹੁਤ ਤਾਕਤਵਰ'],
 'ps': [u'ډیره قوي'],
 'kn': [u'ತುಂಬಾ ಬಲಶಾಲಿ'],
 'sk': [u'veľmi silný'],
 'zh': [u'非常强壮'],
 'th': [u'แข็งแรงมาก'],
 'ta': [u'மிகவும் திடமான'],
 'yi': [u'זייער שטאַרק'],
 'hi': [u'बहुत ताकतवर', u'बहुत तेज़', u'काफी तेज़', u'ज़ोरदार', u'bahut tez', u'kaphi tez', u'zoradara', u'zoradar', u'zoradaar'],
 'uk': [u'дуже сильний'],
 'af': [u'baie sterk'],
 'da': [u'meget stærk'],
 'kk': [u'Өте күшті'],
 'ar': [u'قوي جدا'],
 'es': [u'muy fuerte', u'muy poderoso', u'fuertísimo', u'fuertisimo', u'tremendo', u'muy violento', u'muy violenta'],
 'hu': [u'nagyon erős'],
 'it': [u'molto forte', u'fortissimo', u'fortissima', u'tremendo'],
 'mt': [u'b&#39;saħħtu ħafna'],
 'ur': [u'بہت مضبوط'],
 'tl': [u'napakalakas'],
 'en': [u'very strong', u'massive'],
 'lt': [u'labai stipru'],
 'cs': [u'velmi silný'],
 'ko': [u'매우 강한'],
 'tr': [u'çok güçlü'],
 'te': [u'చాలా బలమైన'],
 'ml': [u'വളരെ ശക്തമായ'],
 'si': [u'ඉතා ශක්තිමත්'],
 'id': [u'sangat kuat'],
 'de': [u'sehr stark'],
 'bn': [u'সুদৃঢ়'],
 'et': [u'väga tugev'],
 'el': [u'πολύ δυνατύς', u'πολύ δυνατύ', u'πολύ δυνατός', u'πολύ δυνατό'],
 'ne': [u'धेरै बलियो'],
 'sv': [u'väldigt stark'],
 'mi': [u'rawa te kaha'],
 'ro': [u'foarte puternic'],
 'ha': [u'karfi'],
 'jw': [u'kuat banget'],
 'ig': [u'ike'],
 'fi': [u'erittäin vahva'],
 'pl': [u'bardzo silny'],
 'hmn': [u'very strong'],
 'zh-CN': [u'非常强壮'],
 'mk': [u'многу јако']
}


keywords[u'destroyed'] = {
 'eu': [u'suntsitu'],
 'vi': [u'phá hủy'],
 'gu': [u'નાશ'],
 'az': [u'məhv'],
 'la': [u'destroyed'],
 'ga': [u'scriosta'],
 'sl': [u'uničena'],
 'bs': [u'porušen'],
 'ru': [u'разрушенный'],
 'mn': [u'устгасан'],
 'ceb': [u'gilaglag'],
 'st': [u'timetsoa'],
 'ca': [u'destruït'],
 'lo': [u'ຖືກທໍາລາຍ'],
 'ny': [u'anawononga'],
 'zu': [u'wabhubhisa'],
 'zh-TW': [u'銷毀'],
 'be': [u'разбураны'],
 'so': [u'baabbi&#39;iyey'],
 'gl': [u'destruído'],
 'hy': [u'ոչնչացվել'],
 'sr': [u'уништена'],
 'su': [u'ancur'],
 'ja': [u'破壊されました', u'震度7'],
 'eo': [u'destroyed'],
 'ka': [u'განადგურდა'],
 'mr': [u'नष्ट'],
 'pt': [u'destruído', u'destruida', u'destruidos', u'destruidas'],
 'sw': [u'kuharibiwa'],
 'nl': [u'vernietigd'],
 'km': [u'បំផ្លាញ'],
 'fr': [u'détruit', u'détruite', u'détruits', u'détruites', u'detruit'],
 'yo': [u'run'],
 'is': [u'eytt'],
 'no': [u'ødelagt'],
 'cy': [u'dinistrio'],
 'fa': [u'نابود'],
 'lv': [u'iznīcināti'],
 'ms': [u'dimusnahkan'],
 'iw': [u'נהרס'],
 'hr': [u'uništena'],
 'uz': [u'vayron'],
 'my': [u'ဖျက်ဆီးပစ်'],
 'sq': [u'i shkatërruar'],
 'tg': [u'нобуд'],
 'bg': [u'унищожен'],
 'mg': [u'rava'],
 'ht': [u'detwi'],
 'pa': [u'ਨੂੰ ਤਬਾਹ'],
 'ps': [u'ډیره قوي'],
 'kn': [u'ನಾಶ'],
 'sk': [u'zničený'],
 'zh': [u'销毁'],
 'th': [u'ทำลาย'],
 'ta': [u'அழிக்கப்பட்ட'],
 'yi': [u'חרובֿ'],
 'hi': [u'नष्ट किया हुआ'],
 'uk': [u'зруйнований'],
 'af': [u'vernietig'],
 'da': [u'ødelagt'],
 'kk': [u'қираған'],
 'ar': [u'دمر'],
 'es': [u'destruido', u'destruida', u'destruidos', u'destruidas'],
 'hu': [u'elpusztított'],
 'it': [u'distrutto', u'distrutta', u'distrutti', u'distrutte'],
 'mt': [u'meqruda'],
 'ur': [u'کو تباہ کر دیا'],
 'tl': [u'nawasak'],
 'en': [u'destroyed'],
 'lt': [u'sugriautas'],
 'cs': [u'zničený'],
 'ko': [u'의해 파괴됨'],
 'tr': [u'yerlebir edilmiş'],
 'te': [u'ధ్వంసమైంది'],
 'ml': [u'നശിപ്പിച്ചു'],
 'si': [u'විනාශ'],
 'id': [u'musnah'],
 'de': [u'kaputt gemacht'],
 'bn': [u'বিনষ্ট'],
 'et': [u'hävitatud'],
 'el': [u'καταστράφηκε από'],
 'ne': [u'नष्ट गरेको'],
 'sv': [u'förstörd'],
 'mi': [u'ngaro'],
 'ro': [u'distrus'],
 'ha': [u'hallaka'],
 'jw': [u'numpes'],
 'ig': [u'ebibi'],
 'fi': [u'tuhonnut'],
 'pl': [u'zniszczony'],
 'hmn': [u'destroyed'],
 'zh-CN': [u'销毁'],
 'mk': [u'уништени']
}

keywords[u'haha'] = {
 'ko': [u'하하', u'도니는 다르게', u'LOL'],
 'ga': [u'haha', u'hehe', u'lol'],
 'km': [u'haha', u'hehe', u'សើច\u200bឮ\u200bខ្លាំង'],
 'az': [u'Haha', u'hehe', u'LOL'],
 'es': [u'jaja', u'jeje', u'LOL', u'pa tu cola', u'despiertame cuando pase'],
 'ur': [u'ہا ہا', u'ڈیسک', u'lol'],
 'ny': [u'haha', u'hehe', u'SEKANI'],
 'ne': [u'haha', u'हाहा', u'lol'],
 'zu': [u'haha', u'hehe', u'LOL'],
 'sq': [u'haha', u'hehe', u'LOL'],
 'su': [u'haha', u'hehe', u'NGABARAKATAK'],
 'my': [u'haha', u'hehe', u'ဟားဟား'],
 'zh-TW': [u'Haha', u'Hehe', u'大聲笑'],
 'kk': [u'хаха', u'Хехе', u'қатты күлу'],
 'hy': [u'haha', u'hehe', u'LOL'],
 'ka': [u'haha', u'hehe', u'ლოლ'],
 'bs': [u'Haha', u'hehe', u'lol'],
 'mt': [u'haha', u'hehe', u'Lol'],
 'bg': [u'Haha', u'хехе', u'LOL'],
 'gu': [u'haha', u'Hehe', u'હા હા હા'],
 'ht': [u'haha', u'hehe', u'LOL'],
 'iw': [u'haha', u'hehe', u'חחח'],
 'jw': [u'haha', u'hehe', u'LOL'],
 'ta': [u'haha', u'Hehe', u'குபீர்'],
 'hi': [u'haha', u'hehe', u'जबरदस्त हंसी'],
 'kn': [u'haha', u'Hehe', u'LOL'],
 'ca': [u'jaja', u'jeje', u'lol'],
 'lv': [u'haha', u'hehe', u'LOL'],
 'tr': [u'haha', u'hehe', u'LOL', u'gol'],
 'ja': [u'Haha', u'笑', u'笑'],
 'et': [u'haha', u'hehe', u'LOL'],
 'mn': [u'Хаха', u'хэхэ', u'LOL'],
 'lo': [u'haha', u'hehe', u'ຫົວ\u200bດັງໆ'],
 'fa': [u'هاها', u'من خودم', u'LOL'],
 'sw': [u'haha', u'hehe', u'LOL'],
 'cy': [u'haha', u'hehe', u'LOL'],
 'nl': [u'Haha', u'hehe', u'lol'],
 'mk': [u'ха, ха', u'hehe', u'смеење на глас'],
 'af': [u'haha', u'hehe', u'lol'],
 'is': [u'haha', u'Hehe', u'LOL'],
 'tg': [u'Haha', u'hehe', u'ҲА ҲА ҲА'],
 'sk': [u'haha', u'hehe', u'LOL'],
 'ms': [u'haha', u'hehe', u'LOL'],
 'vi': [u'Haha', u'Hehe', u'LOL'],
 'yi': [u'האַהאַ', u'העהע', u'לאָל'],
 'bn': [u'হা হা', u'Hehe', u'হাঃ হাঃ হাঃ'],
 'tl': [u'Haha', u'Hehe', u'lol'],
 'hu': [u'Haha', u'hehe', u'vicces'],
 'gl': [u'haha', u'hehe', u'LOL'],
 'ar': [u'هاها', u'الكالينجيون', u'الضحك بصوت مرتفع'],
 'so': [u'land', u'hehe', u'LOL'],
 'hr': [u'haha', u'hehe', u'LOL'],
 'sl': [u'haha', u'hehe', u'LOL'],
 'id': [u'haha', u'Hehe', u'LOL'],
 'ceb': [u'haha', u'hehe', u'LOL'],
 'it': [u'haha', u'hehe', u'LOL', u'gol'],
 'no': [u'haha', u'Hehe', u'LOL'],
 'si': [u'හාහා', u'hehe', u'LOL'],
 'te': [u'కొత్తపాళీ', u'Hehe', u'LOL'],
 'be': [u'ха-ха', u'хе-хе', u'LOL'],
 'uk': [u'ха-ха', u'хе-хе', u'Лол'],
 'pl': [u'haha', u'Hehe', u'lol'],
 'ro': [u'Haha', u'hehe', u'LAUGH OUT LOUD'],
 'mg': [u'Haha', u'hehe', u'TPT'],
 'ha': [u'haha', u'Hehe', u'LOL'],
 'ig': [u'Haha', u'hehe', u'akpa ọchị'],
 'cs': [u'haha', u'hehe', u'LOL'],
 'pa': [u'ਹਾਹਾ', u'hehe', u'LOL'],
 'ps': [u'هاها', u'هو', u'LOL'],
 'eu': [u'haha', u'hehe', u'LOL'],
 'mi': [u'haha', u'hehe', u'LOL'],
 'uz': [u'haha', u'hehe', u'ahahaha'],
 'mr': [u'छे', u'होतय', u'मोठ्याने हसणे'],
 'ml': [u'.അച്ചായന്റെ', u'കുട്ടേട്ടനാണ്', u'പൊട്ടിച്ചിരിക്കുക'],
 'fr': [u'haha', u'hehe', u'LOL'],
 'pt': [u'haha', u'hehe', u'RI MUITO'],
 'sv': [u'Haha', u'Hehe', u'LOL'],
 'zh-CN': [u'Haha', u'Hehe', u'大声笑'],
 'la': [u'Haha', u'Hehe', u'LOL'],
 'eo': [u'Haha', u'Hehe', u'LOL'],
 'ru': [u'ха-ха', u'хе-хе', u'лол'],
 'hmn': [u'Haha', u'Hehe', u'LOL'],
 'de': [u'haha', u'hehe', u'lol'],
 'en': [u'Haha', u'Hehe', u'LOL', u'earthquake weather'],
 'da': [u'haha', u'hehe', u'LOL'],
 'sr': [u'хаха', u'хехе', u'лол'],
 'st': [u'Haha', u', hehe', u'HA HA HA'],
 'lt': [u'haha', u'hehe', u'daug juoko'],
 'zh': [u'Haha', u'Hehe', u'大声笑'],
 'yo': [u'haha', u'hehe', u'lol'],
 'el': [u'χαχα', u'hehe', u'LOL'],
 'fi': [u'Haha', u'hehe', u'LOL'],
 'th': [u'ฮ่าฮ่า', u'ฮิฮิ', u'ฮ่า ๆ']
}

keywords[u'simulation'] = {
 'af': [u'simulasie', u'toets', u'toetsboor'],
 'ar': [u'محاكاة', u'اختبار', u'اختبار اختبار'],
 'az': [u'simulyasiya', u'test'],
 'be': [u'мадэляванне', u'тэст', u'выпрабаванне свердзела'],
 'bg': [u'симулация', u'тест'],
 'bn': [u'ব্যাজ', u'পরীক্ষা', u'পরীক্ষা ড্রিল'],
 'bs': [u'simulacija', u'test', u'testna bušilica'],
 'ca': [u'simulació', u'prova', u'simulacre'],
 'ceb': [u'pagkalibang', u'pagsulay', u'test drill'],
 'cs': [u'simulace', u'test', u'zkušební vrtačka'],
 'cy': [u'efelychiad', u'prawf', u'profi dril'],
 'da': [u'simulering', u'prøve', u'testboremaskine'],
 'de': [u'Simulation', u'Prüfung', u'Testbohrer'],
 'el': [u'προσομοίωση', u'δοκιμή', u'τρυπάνι δοκιμής'],
 'en': [u'simulation', u'test', u'drill', u'canceled', u'cancelled', u'dropped', u'all clear'],
 'es': [u'simulación', u'prueba', u'simulacro'],
 'et': [u'simulatsioon', u'test', u'katsepuur'],
 'eu': [u'simulazioa', u'proba', u'proba zulagailua'],
 'fa': [u'شبیه سازی', u'تست', u'آزمایش مته'],
 'fi': [u'simulointi', u'testata', u'testipora'],
 'fr': [u'simulation', u'test', u'prouve'],
 'ga': [u'insamhalta', u'scrúdú', u'druil tástála'],
 'gl': [u'simulación', u'proba', u'simulacro'],
 'gu': [u'સિમ્યુલેશન', u'પરીક્ષણ', u'પરીક્ષણ કવાયત'],
 'ha': [u'kwaikwayo', u'gwajin', u'gwaji rawar soja'],
 'hi': [u'सिमुलेशन', u'परीक्षा', u'परीक्षण ड्रिल'],
 'hmn': [u'simulation', u'test', u'drill'],
 'hr': [u'simuliranje', u'test', u'probna'],
 'ht': [u'simulation', u'tès', u'egzèsis egzamen an'],
 'hu': [u'tettetés', u'teszt', u'próbafúró'],
 'hy': [u'սիմուլյացիա', u'փորձարկում', u'փորձարկման ակտ'],
 'id': [u'simulasi', u'uji', u'uji coba'],
 'ig': [u'nyocha', u'ule', u'ule ule'],
 'is': [u'uppgerð', u'próf', u'prófbora'],
 'it': [u'simulazione', u'test', u'prova'],
 'iw': [u'סימולציה', u'מִבְחָן', u'מקדחה הבדיקה'],
 'ja': [u'シミュレーション', u'テスト', u'ドリル'],
 'jw': [u'simulasi', u'test'],
 'ka': [u'სიმულაცია', u'გამოცდა', u'ტესტი საბურღი'],
 'kk': [u'симуляция', u'сынақ', u'сынақ бұрғысы'],
 'km': [u'ការក្លែងធ្វើ', u'សាកល្បង', u'សាកល្បងសមយុទ្ធ'],
 'kn': [u'ಸಿಮ್ಯುಲೇಶನ್', u'ಪರೀಕ್ಷೆ', u'ಟೆಸ್ಟ್ ಡ್ರಿಲ್'],
 'ko': [u'시뮬레이션', u'테스트', u'시험 훈련'],
 'la': [u'simulation', u'test', u'test drill'],
 'lo': [u'simulation', u'ທົດສອບ', u'ທົດສອບເຈາະ'],
 'lt': [u'modeliavimas', u'bandymas', u'bandymo grąžtas'],
 'lv': [u'simulācija', u'pārbaude', u'pārbaudes urbis'],
 'mg': [u'simulation', u'fitsapana', u'test drill'],
 'mi': [u'whakahoutanga', u'whakamātautau', u'whakamātautau'],
 'mk': [u'симулација', u'тест', u'тест вежба'],
 'ml': [u'സിമുലേഷൻ', u'പരീക്ഷിക്കുക', u'ടെസ്റ്റ് ഡ്രിൽ'],
 'mn': [u'дууриамал', u'Туршилт', u'туршилтын өрөм'],
 'mr': [u'सिम्युलेशन', u'चाचणी', u'चाचणी धान्य पेरण्याचे यंत्र'],
 'ms': [u'simulasi', u'ujian', u'ujian gerudi'],
 'mt': [u'simulazzjoni', u'test', u'drill tat-test'],
 'my': [u'ခြင်း simulation', u'စမ်းသပ်', u'စမ်းသပ်လေ့ကျင့်ခန်း'],
 'ne': [u'नक्कली', u'परीक्षण', u'परीक्षण ड्रिल'],
 'nl': [u'simulatie', u'test', u'testoefening'],
 'no': [u'simulering', u'test', u'testboring'],
 'ny': [u'kuyimilira', u'mayesero', u'kupima'],
 'pa': [u'ਸਿਮੂਲੇਸ਼ਨ', u'ਟੈਸਟ', u'ਟੈਸਟ ਮਸ਼ਕ'],
 'ps': [u'نقلي'],
 'pl': [u'symulacja', u'test', u'wiertło testowe'],
 'pt': [u'simulação', u'teste'],
 'ro': [u'simulare', u'test'],
 'ru': [u'моделирование', u'контрольная работа', u'тестовая дрель'],
 'si': [u'සමාකරණ', u'පරීක්ෂණය', u'පරීක්ෂණ සරඹ'],
 'sk': [u'simulácia', u'test', u'skúšobný vrták'],
 'sl': [u'simulacija', u'test', u'testni vrtalnik'],
 'so': [u'jilicsanaanta', u'imtixaan', u'tijaabinta tijaabada'],
 'sq': [u'simulim', u'provë', u'stërvitja provë'],
 'sr': [u'симулација', u'тест', u'тестна бушилица'],
 'st': [u'ho bapisa', u'teko', u'ho hlahloba liteko'],
 'su': [u'simulasi', u'nguji', u'bor test'],
 'sv': [u'simulering', u'test'],
 'sw': [u'simulation', u'mtihani', u'jaribio la mtihani'],
 'ta': [u'உருவகப்படுத்துதல்', u'சோதனை', u'சோதனை பயிற்சி'],
 'te': [u'అనుకరణ', u'పరీక్ష', u'పరీక్ష డ్రిల్'],
 'tg': [u'Симулятсия', u'озмоиш', u'озмоиши озмоишӣ'],
 'th': [u'จำลอง', u'ทดสอบ', u'เจาะทดสอบ'],
 'tl': [u'simulation', u'pagsusulit', u'pagsubok drill'],
 'tr': [u'simülasyon', u'Ölçek', u'deneme', u'tatbikat', u'talim'],
 'uk': [u'симуляція', u'тест', u'тестова свердла'],
 'ur': [u'نقلی', u'ٹیسٹ', u'ٹیسٹ ڈرل'],
 'uz': [u'simulyatsiya', u'sinov', u'sinovli matkap'],
 'vi': [u'mô phỏng', u'kiểm tra', u'kiểm tra khoan'],
 'yi': [u'סימיאַליישאַן', u'test', u'פּרובירן בויער'],
 'yo': [u'kikopa', u'idanwo', u'idanwo idanwo'],
 'zh': [u'模拟', u'测试', u'测试演习'],
 'zh-CN': [u'模拟', u'测试', u'测试演习'],
 'zh-TW': [u'模擬', u'測試', u'測試演習'],
 'zu': [u'ukulingisa', u'ukuhlolwa', u'i-drill test']
}

spam = [
    "Lionel",
    "Messi",
    "Cristiano",
    "Ronaldo",
    "Neymar",
    "Mbappe",
    "Salah",
    "Kevin",
    "De Bruyne",
    "Robert",
    "Lewandowski",
    "Sergio",
    "Aguero",
    "Luka",
    "Modric",
    "Kylian",
    "Hazard",
    "Paul",
    "Pogba",
    "Kroos",
    "Sadio",
    "Virgil",
    "Van Dijk",
    "Vertonghen",
    "Christian",
    "Eriksen",
    "De Gea",
    "Joshua",
    "Kimmich",
    "Alisson",
    "Becker",
    "Leroy",
    "Raheem",
    "Sterling",
    "Romelu",
    "Lukaku",
    "Marc-Andre",
    "Ter Stegen",
    "Gareth",
    "Marcus",
    "Rashford",
    "Heung-min",
    "Marcelo",
    "Vieira",
    "Ronaldo",
    "Firmino",
    "Roberto",
    "Firmino",
    "Alexander-Arnold",
    "Georginio",
    "Wijnaldum",
    "Suarez",
    "Lampard",
    "Andres",
    "Iniesta",
    "Gerard",
    "Jordi",
    "N'Golo",
    "Rakitic",
    "Silva",
    "Mohamed",
    "Elneny",
    "Serge",
    "Aurier",
    "Hector",
    "Bellerin",
    "Stones",
    "Riyad",
    "Mahrez",
    "Bernardo",
    "Kostas",
    "Manolas",
    "Thomas",
    "Partey",
    "Houssem",
    "Aouar",
    "Memphis",
    "Depay",
    "Frenkie",
    "De Jong",
    "David",
    "Alaba",
    "Caglar",
    "Soyuncu",
    "Wilfred",
    "Ndidi",
    "Rodriguez",
    "Edinson",
    "Cavani",
    "Sergio",
    "Reguilon",
    "Godin",
    "Chiellini",
    "Goretzka",
    "Nabil",
    "Fekir",
    "Thiago",
    "Alcantara",
    "Federico",
    "Hirving",
    "Lozano",
    "Hakim",
    "Ziyech",
    "Stefan",
    "Savic",
    "Alejandro",
    "Gomez",
    "Cancelo",
    "Fabinho",
]
